### PR TITLE
Added some asv benchmarks teardown functions (#17616)

### LINKED ISSUE #17616: Add teardowns in asv benchmarks
Per @jreback's comment [here](https://github.com/pandas-dev/pandas/pull/17168/files/f0089d14f219c302ab62af41c50218704d87d4fb#r139321194), we should have teardowns in asv benchmarks, especially in IO benchmarks where we are creating files.

### PR DESCRIPTION
**Pull request by dmanikowski-reef**
- [x] closes #17616

### CODE REVIEW

**Comment by ppolewicz** [comment]
This PR contains 79 commits. Can you please rebase your changes on top of upstream master?

**Comment by brychlicki-reef** [comment]
~@dmanikowski-reef 
First, your commit message should include one of the tags described at https://pandas.pydata.org/pandas-docs/stable/contributing.html#committing-your-code
, without much thinking I'd shoot for `PERF: Performance improvement`~

my mistake, you do have the tag, I misread PR name for commit name, dumb me, sorry

**Comment by dmanikowski-reef** [comment]
Can anyone take a look at this or give some feedback? Thanks to @brychlicki-reef the number of commits has been fixed :)

**Comment by brychlicki-reef** [comment]
Anyone reviewing, please note https://github.com/pandas-dev/pandas/issues/17616#issuecomment-337947340

I cannpt review it for the moment but if no one volunteers in few days, I will try to get back to it

**Review by ghost — APPROVED** [review]
Looks good.

**Comment by ghost** [comment]
@dmanikowski-reef I've made a _"recommit"_ with `git commit --amend --no-edit && git push --force-with-lease` to trigger a new build after hooking up `Circle CI` and `AppVeyor`.
Just letting you know not to worry :wink:

**Review by mzukowski-reef — APPROVED** [review]

**Pull request merged**
